// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCountdown(arg1) {
  return window['go']['main']['App']['DeleteCountdown'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function ExportGradesCSV() {
  return window['go']['main']['App']['ExportGradesCSV']();
}

export function ExportGradesPDF() {
  return window['go']['main']['App']['ExportGradesPDF']();
}

export function ExportTimetableICS(arg1, arg2) {
  return window['go']['main']['App']['ExportTimetableICS'](arg1, arg2);
}

export function GetAbsenceStats() {
  return window['go']['main']['App']['GetAbsenceStats']();
}

export function GetAbsences() {
  return window['go']['main']['App']['GetAbsences']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBellSchedule() {
  return window['go']['main']['App']['GetBellSchedule']();
}

export function GetChangesSinceLastOpen() {
  return window['go']['main']['App']['GetChangesSinceLastOpen']();
}

export function GetCountdowns() {
  return window['go']['main']['App']['GetCountdowns']();
}

export function GetCurrentAccount() {
  return window['go']['main']['App']['GetCurrentAccount']();
}

export function GetCurrentTheme() {
  return window['go']['main']['App']['GetCurrentTheme']();
}

export function GetCustomColor() {
  return window['go']['main']['App']['GetCustomColor']();
}

export function GetExams() {
  return window['go']['main']['App']['GetExams']();
}

export function GetGrades() {
  return window['go']['main']['App']['GetGrades']();
}

export function GetHomework(arg1) {
  return window['go']['main']['App']['GetHomework'](arg1);
}

export function GetLocalProfile() {
  return window['go']['main']['App']['GetLocalProfile']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetStudentDetail() {
  return window['go']['main']['App']['GetStudentDetail']();
}

export function GetSubjectColors() {
  return window['go']['main']['App']['GetSubjectColors']();
}

export function GetTeacherProfile(arg1) {
  return window['go']['main']['App']['GetTeacherProfile'](arg1);
}

export function GetTimetable(arg1, arg2) {
  return window['go']['main']['App']['GetTimetable'](arg1, arg2);
}

export function GetUnreadCount() {
  return window['go']['main']['App']['GetUnreadCount']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoadEntries() {
  return window['go']['main']['App']['LoadEntries']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkAllRead() {
  return window['go']['main']['App']['MarkAllRead']();
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function OpenDKT() {
  return window['go']['main']['App']['OpenDKT']();
}

export function OpenDeveloper() {
  return window['go']['main']['App']['OpenDeveloper']();
}

export function OpenGitHub() {
  return window['go']['main']['App']['OpenGitHub']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SaveCountdown(arg1) {
  return window['go']['main']['App']['SaveCountdown'](arg1);
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function SaveLocalProfile(arg1) {
  return window['go']['main']['App']['SaveLocalProfile'](arg1);
}

export function SearchInstitutes(arg1) {
  return window['go']['main']['App']['SearchInstitutes'](arg1);
}

export function SetBellSchedule(arg1) {
  return window['go']['main']['App']['SetBellSchedule'](arg1);
}

export function SetCustomColor(arg1) {
  return window['go']['main']['App']['SetCustomColor'](arg1);
}

export function SetSubjectColor(arg1, arg2) {
  return window['go']['main']['App']['SetSubjectColor'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function ToggleCountdown(arg1) {
  return window['go']['main']['App']['ToggleCountdown'](arg1);
}
