// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function DeleteCountdown(arg1:number):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function ExportGradesCSV():Promise<string>;

export function ExportGradesPDF():Promise<string>;

export function ExportTimetableICS(arg1:string,arg2:string):Promise<string>;

export function GetAbsenceStats():Promise<Array<models.SubjectAbsenceStat>>;

export function GetAbsences():Promise<Array<models.Absence>>;

export function GetAccounts():Promise<Array<models.AccountInfo>>;

export function GetBellSchedule():Promise<Array<models.BellPeriod>>;

export function GetChangesSinceLastOpen():Promise<Array<models.Change>>;

export function GetCountdowns():Promise<Array<models.Countdown>>;

export function GetCurrentAccount():Promise<models.AccountInfo>;

export function GetCurrentTheme():Promise<string>;

export function GetCustomColor():Promise<string>;

export function GetExams():Promise<Array<models.Exam>>;

export function GetGrades():Promise<Array<models.Grade>>;

export function GetHomework(arg1:string):Promise<Array<models.Homework>>;

export function GetLocalProfile():Promise<models.LocalProfile>;

export function GetNotifications():Promise<Array<models.Notification>>;

export function GetStudentDetail():Promise<models.StudentDetail>;

export function GetSubjectColors():Promise<Array<models.SubjectColor>>;

export function GetTeacherProfile(arg1:string):Promise<models.TeacherProfile>;

export function GetTimetable(arg1:string,arg2:string):Promise<Array<models.Lesson>>;

export function GetUnreadCount():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function LoadEntries():Promise<Array<main.FuzetEntry>>;

export function Login(arg1:models.Institute,arg2:string,arg3:string):Promise<models.AccountInfo>;

export function Logout():Promise<void>;

export function MarkAllRead():Promise<void>;

export function MarkRead(arg1:number):Promise<void>;

export function OpenDKT():Promise<void>;

export function OpenDeveloper():Promise<void>;

export function OpenGitHub():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SaveCountdown(arg1:models.Countdown):Promise<models.Countdown>;

export function SaveEntry(arg1:main.FuzetEntry):Promise<void>;

export function SaveLocalProfile(arg1:models.LocalProfile):Promise<void>;

export function SearchInstitutes(arg1:string):Promise<Array<models.Institute>>;

export function SetBellSchedule(arg1:Array<models.BellPeriod>):Promise<void>;

export function SetCustomColor(arg1:string):Promise<void>;

export function SetSubjectColor(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SwitchAccount(arg1:string):Promise<models.AccountInfo>;

export function ToggleCountdown(arg1:number):Promise<void>;
